login/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import include, re_path


app_name = "login"
urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html")),
    path('logout/', LogoutView.as_view()),
    path('userlanding/', views.user_reports),
    path('adminlanding/',views.admin_landing_view),
    path('report/', views.report),
    path('publicreports/', views.public_reports),
    path('publicreports/newest', views.public_reports_newest),
    path('publicreports/votes', views.public_reports_votes),
    path('viewreports/', views.admin_view_reports),
    path('adminreportview/', views.review_reports),
    path('adminreportview/<int:pk>/', views.admin_specific_report_view, name='admin_specific_report_view'),
    path('publicreports/<int:pk>/', views.public_specific_report_view, name='public_specific_report_view'),
    re_path(r'^delete/admin/(?P<pk>[0-9]+)/$', views.report_delete_admin, name='report_delete_admin'),
    re_path(r'^delete/user/(?P<pk>[0-9]+)/$', views.report_delete, name='report_delete'),
    
    path('sent/',views.email),
    path('new_reports/',views.new_reports),
    path('in_progress_reports/',views.in_progress_reports),
    path('resolved_reports/',views.resolved_reports),
    path('admin_public_reports/',views.admin_public_reports),
    path('editreport/<int:pk>/',views.edit_report),
]

whistleblowingsite/urls.py
from django.contrib import admin
from django.urls import path, include
from login import views


urlpatterns = [
    path("", include("login.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('home/', views.DocumentCreateView.as_view()),

]

login/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Evidence(models.Model):
    uploaded_at = models.DateTimeField(auto_now_add=True)
    upload = models.FileField()

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.uploaded_at <= now

class Report(models.Model):
    class Statuses(models.TextChoices):
        NEW = 'NEW', 'New'
        IN_PROGRESS = 'INP', 'In Progress'
        RESOLVED = 'RES', 'Resolved'
    userID = models.CharField(max_length = 200)
    report = models.TextField(max_length = 500, default="")
    className = models.CharField(max_length = 200)
    professorName = models.CharField(max_length = 200)
    studentName = models.CharField(max_length = 200)
    rating = models.CharField(max_length = 200)
    workType = models.CharField(max_length = 200)
    fileLink = models.CharField(max_length = 500)
    status = models.CharField(max_length = 10)
    feedback = models.TextField(max_length = 500)
    professor_email = models.CharField(max_length = 200)
    email_prof = models.BooleanField(default=True)
    private = models.BooleanField(default=True)
    reported = models.BooleanField(default=False)
    email_status= models.BooleanField(default=False)
    pub_date = models.DateTimeField(auto_now_add=True)
    votes = models.IntegerField(default=0)
    file_type = models.CharField(max_length = 10, default="pdf")

class Comments(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    comment = models.TextField(max_length = 500)
    pub_date = models.DateTimeField(auto_now_add=True)

login/forms.py
from django import forms
from login.models import Report

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields=['userID', 'report', 'className', 'professorName', 'studentName', 
                'rating','workType','fileLink','status','feedback', 'professor_email', 'email_prof', 'private', 'reported']

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver
from login.models import Report, Evidence, Comments
#from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.core.mail import EmailMessage
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.db.models import Q
from .forms import ReportForm
from django.utils import timezone
from django.template.defaulttags import register
import re

def check_file_name(s):
    return bool(re.match(r'^[\w.]+$', s))

@register.filter(name='isjpg')
def split(value): 
 
    ext = value.split(".")[-1]
    return ext == '.jpg'

# Create your views here.
class DocumentCreateView(CreateView):
    model = Evidence
    fields = ['upload', ]
    success_url = '/home'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        documents = Evidence.objects.all()
        context['documents'] = documents
        return context

@receiver(user_logged_in)
def redirect_after_google_login(sender, request, user, **kwargs):
    print(f"Signal received from {sender}")
    
    #return redirect('adminlanding/')
    if user.groups.filter(name='site admin').exists():
        print(f"I am an admin")
        return redirect('adminlanding/')
    else:
        print(f"I am a user")
        return redirect('userlanding/')


def home(request):
    return render(request, "login/home.html") 

def logout_view(request):
    logout(request)
    return redirect("/")

def admin_view_reports(request):
    return render(request, "admin_view_reports.html")

def public_reports(request):
    if request.method == "POST":
        search = request.POST.get('search')
        public_reports = Report.objects.filter(private=False).order_by("-pub_date")
        if search == "":
            return render(request, "public_reports.html", {"reports": public_reports})
        public_reports = public_reports.filter( Q(className__icontains=search) | Q(professorName__icontains=search) | Q(studentName__icontains=search))
        public_reports.filter(private=False)
        return render(request, "public_reports.html", {"reports": public_reports})
    
    public_reports = Report.objects.filter(private=False).order_by("-pub_date")
    return render(request, "public_reports.html", {"reports": public_reports})

def user_landing_view(request):
    ## retrieve user's name through database lookup
    print(f"requested user landing view")
    name = "name"
    return render(
        request, 
        "user_landing_page.html", 
    )


def admin_landing_view(request):
    print(f"requested admin landing view")
    return render(
        request, 
        "admin_landing_page.html",
    )

def report(request):
    if request.method == 'POST':
        filetype=""
        fileLink = ""
        try:
            upload=request.FILES['filename']
            print(upload)
            if not check_file_name(upload.name):
                return render(
                request,
                "report_page.html",
                {
                    "error_message": "File name must be alphanumerical.","success_message":"",
                },
                )
            filetype = upload.name.split(".")[-1]
            print(filetype)
            if filetype != "jpg" and filetype != "txt" and filetype != "pdf":
                return render(
                request,
                "report_page.html",
                {
                    "error_message": "File type must be jpg, txt, or pdf.","success_message":"",
                },
                )
            
            evidence = Evidence(upload=upload)
            print(evidence)
            fileLink = evidence.upload.url
            print("filelink:" + fileLink)
            evidence.save()
        except Exception as e:
            fileLink=""
            print(str(e))
            if (str(e) != "'filename'"):
            
                return render(
                    request,
                    "report_page.html",
                    {
                        "error_message": str(e),
                    },
                    )
        userID = request.POST['userID']
        className = request.POST['className']
        professorName = request.POST['professorName']
        studentName = request.POST['studentName']
        rating = request.POST.get('rating')
        workType = request.POST.get('workType')
        professor_email = request.POST['professor_email']
        email_prof = request.POST.get('email_prof')
        report = request.POST['report']
        privacy = request.POST.get('privacy')
        status = "New"
        feedback = ""

        print(rating)
        
        # print(fileLink)
        # print(privacy)
        
        if len(className) > 200:
            return render(
                    request,
                    "report_page.html",
                    {
                        "error_message": "Class name must be under 200 characters.","success_message":"",
                    },
                    )
            
        if len(report.split(" ")) > 500 or len(report) > 10000:
            return render(
                    request,
                    "report_page.html",
                    {
                        "error_message": "Report must be under 500 words and 10000 characters.","success_message":"",
                    },
                    )
            
        if len(professorName) > 200:
            return render(
                    request,
                    "report_page.html",
                    {
                        "error_message": "Professor name must be under 200 characters.","success_message":"",
                    },
                    )
            
        if len(studentName) > 200:
            return render(
                    request,
                    "report_page.html",
                    {
                        "error_message": "Student name must be under 200 characters.", "success_message":"",
                    },
                    ) 
            
        if len(professor_email) > 200:
            return render(
                    request,
                    "report_page.html",
                    {
                        "error_message": "Professor email must be under 200 characters.","success_message":"",
                    },
                    ) 
        
        if privacy is None:
            privacy_boolean = True
            privacy = True
        else:
            privacy_boolean = False
            privacy = False
        
        if(email_prof == "email_prof" or email_prof == "on"):
            email_prof_boolean = True
            email_prof = True
        else:
            email_prof_boolean = False
            email_prof = False
        
        if userID == "":
            userID = "Anonymous"
        
        if email_prof == None or report == "" or className == "" or professorName == "" or studentName == "" or rating == None or workType == None or status == "":
            print("not enough fields")
            return render(
                request,
                "report_page.html",
                {
                    "error_message": "You are missing one or more fields.","success_message":"",
                },
                )
        if email_prof_boolean:
            try:
                if professor_email.strip()=="":
                    raise ValidationError("Invalid email")
                validate_email(professor_email)
            except ValidationError as e:
                return render(
                    request,
                    "report_page.html",
                    {
                        "error_message": "You must enter a valid email.","success_message":"",
                    },
                    )
        print("creating object")
        Report.objects.create(file_type=filetype, userID = userID, report = report, className = className, professorName = professorName, studentName = studentName, rating = rating, workType = workType, fileLink = fileLink, status=status, feedback=feedback, email_prof = email_prof_boolean, professor_email = professor_email, private = privacy_boolean)
        return render(
                request,
                "report_page.html",
                {
                    "error_message": "", "success_message":"Your report has successfully been submitted",
                },
                )
    return render(
                request,
                "report_page.html",
                {
                    "error_message": "", "success_message":"",
                },
                )
            

@login_required
def user_reports(request):
    print(f"requested user view reports")
    name = "name"
    reports = Report.objects.filter(userID=request.user.email)
    return render(request, 'user_reports.html', {'reports': reports})


    
def review_reports(request):
    reports = Report.objects.all()
    return render(
        request,
        "review_reports.html",
        {'reports' : reports},
    )

def public_reports_newest(request):
    public_reports = Report.objects.filter(private=False).order_by("-pub_date")
    return render(request, "public_reports.html", {"reports": public_reports})

def public_reports_votes(request):
    public_reports = Report.objects.filter(private=False).order_by("-votes")
    return render(request, "public_reports.html", {"reports": public_reports})


def new_reports(request):
    new_reports = Report.objects.filter(status='New')
    return render(request, "new_reports.html", {"reports": new_reports})

def in_progress_reports(request):

login/templates/admin_landing_page.html
<!DOCTYPE html>
{% load socialaccount %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<style>
  body {
      font-family: 'Lato', sans-serif;
  }
  </style>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap">
<html lang="en">
  {% include 'login/admin_navbar.html' %}

    <body>
        <div class="position-absolute top-50 start-50 translate-middle">
          <p class="fs-1 d-flex justify-content-center">You are an admin!</p>
          <p class="fs-1 d-flex justify-content-center">Email: {{user.email}}</p>
          <p class="fs-1 d-flex justify-content-center">Name: {{user}}</p>

        </div>
    </body>
    <script>
      document.addEventListener('DOMContentLoaded', function () {
      var Home = document.getElementById('Home');
      if (Home) {
        Home.style.backgroundColor = 'rgb(242, 204, 143)';
        Home.style.height = 'calc(100% + 25px)';
        Home.style.transform = 'translateY(-7px)';
        Home.style.borderBottomLeftRadius = '8px';
        Home.style.borderBottomRightRadius = '8px';
      }
    });
    </script>
</html>

login/templates/admin_public_reports.html
<!DOCTYPE html>
{% load socialaccount %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<style>
  @media (max-width: 1085px) {
    .body {
      margin-right: -100px;
      font-family: 'Lato', sans-serif;
    }


    .row.row-cols-1.g-4 {
      width: 100%;
      justify-content: center;
      left: 0;
      right: 0;
      margin: 0 auto;
    }

    .report {
      width: 100%;
    }

    .col {
      width: 100% !important;
      margin: 1vw 0;
    }

    .card,
    .card-body,
    .row {
        width: calc(2 * 44.5vw - 40px) !important;
      }

    .card-body textarea {
      width: calc(88vw - 105px) !important;
      margin-bottom: 10px;
      padding: 10px;
      resize: vertical;
      min-height: 100px;
    }

    .summary {
      width: 90% !important;
      margin: 0 auto 1vh auto;
    }

    .details {
      width: calc(88vw - 65px) !important;
    }

    .expandcollapse {
      width: calc(88vw - 65px) !important;
    }

    .information {
      margin-left: auto;
      margin-right: auto;
      width: 90% !important;
      display: flex;
      flex-direction: row;
      align-items: center;
    }

    .submit_status_and_update {
      width: 45% !important;
      height: auto !important;
      display: flex;
      justify-content: center;
    }

    .submit_status_and_update_box {
      flex-wrap: wrap;
      width: auto !important;
      height: auto !important;
      display: flex;
      justify-content: space-around;
      align-items: center;
    }

    .quickinfo {
      width: 45% !important;
      height: auto !important;
      margin-bottom: 10px;
    }

    .edit,
    .delete {
      width: 19vw !important;
    }

    .rating_email {
      width: max(10vw, 20vh);
      height: max(10vw, 20vh);
    }

    .private {
      width: auto;
      height: 8vh;
    }

    #ReportDetails,
    #display,
    #ExpandCollapse,
    #arrowImage {
      width: calc(2 * 40.5vw) !important;
    }

    .textarea-container {
      width: 100%;
      display: flex;
      justify-content: center;
      margin-top: 20px;
    }
  }
</style>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap">
<html lang="en">
{% include 'login/admin_navbar.html' %}

<body style="background-color: rgb(224, 122, 95); margin-top: 120px;" class="body">

  {% if user.is_authenticated %}
  {% if user.groups.exists %}
  {% for group in user.groups.all %}
  {% if group.name != 'site admin' %}
  {% endif %}
  {% endfor %}
  {% else %}
  <meta http-equiv="refresh" content="0; url=/userlanding/" />
  {% endif %}
  {% endif %}
  <div class="container mt-5">
    <div class="row row-cols-1 g-4" style="width: 100vw; position: absolute; justify-content: center; left: 0; right: 0; margin: 0 auto;">
      {% for report in reports %}
      <div class="col" style="width: calc(44.5vw - 18px); margin: 1vw;">
        <div class="card" id="report_card{{report.id}}"
          style="margin-left: -12px; width: calc(44.5vw - 20px); height: auto; background-color: rgb(242, 204, 143); border: 0px;">
          <div class="card-body">
            <div class="summary"
              style="width: auto; height: auto; padding-top: 5px; padding-bottom: 5px; border-radius: 5px; background-color: #f0f0f0; text-align: center; align-items: center; padding-top: 8px; margin-bottom: 1vh;">
              {{report.userID}} reported <strong>{{ report.studentName.capitalize }}</strong> for their work in <strong>{{report.className }}</strong> taught by <strong>{{ report.professorName.capitalize}}</strong><br>
            </div>

            <div style="display: flex; width: 40vw; height: 15vh; margin-bottom: 1vh;" class="information">
              <div class="quickinfo"
                style="width: 49%; height: 95%; display: inline-block; margin-right: 10px; margin-top: 3.9px; background-color: #f0f0f0; border-radius: 5px;">
                <div style="padding: 5px 10px; box-sizing: border-box; width: 100%; height: 30px; margin-bottom: 3px;">
                  <div style="display: flex; align-items: center;">
                    <p style="font-weight: bold; padding-left: 5px; width: auto;">Work Type: </p>
                    <p style="padding-left: 10px; width: auto;">{{ report.workType.capitalize }}</p>
                  </div>
                </div>
                <div
                  style="width: 90%; height: 5px; border-radius: 3px; background-color: rgb(242, 204, 143); margin: auto;">
                </div>
                <div style="padding: 3px 10px; top: 0; width: 100%; height: 30px; margin-bottom: 3px;">
                  <div style="display: flex; align-items: center;">
                    <p style="font-weight: bold; padding-left: 5px; width: auto;">Status: </p>
                    <p style="padding-left: 10px; width: auto;">{{ report.status.capitalize }}</p>
                  </div>
                </div>
              </div>

              <div style="width: 20vw; display: inline-block; height: 15vh; margin-right: -5px;"
                class="submit_status_and_update">
                <div style="display: flex; justify-content: space-around; align-items: center; height: 15vh;"
                  class="submit_status_and_update_box">
                  {% if report.rating.capitalize == "Positive" %}
                  <img class="rating_email" style="rotate: 90deg; width: auto; height: 8vh;"
                    src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhD2a2uzprPRdusoiSCTdrF5I6j5T_nY4FD-PU4e62iy0B77leCdAAiBhAcwa5R_p40HiDPkoX0Q_cBKONCbj3O7tq-lxhO2paTdCivtc2lG9hL_w5aVHxhH6cz5zUnGqAEcpU0kt2cGPVf5V6DmIU9AOHWaQXNCyh7g4cR2GgmxqdJQA1mQHb0pas6ZW8/s334/Screenshot_2024-04-20_at_4.22.10_PM-removebg-preview.png">
                  {% elif report.rating.capitalize == "Negative" %}
                  <img class="rating_email" style="width: auto; height: 8vh;"
                    src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhD2a2uzprPRdusoiSCTdrF5I6j5T_nY4FD-PU4e62iy0B77leCdAAiBhAcwa5R_p40HiDPkoX0Q_cBKONCbj3O7tq-lxhO2paTdCivtc2lG9hL_w5aVHxhH6cz5zUnGqAEcpU0kt2cGPVf5V6DmIU9AOHWaQXNCyh7g4cR2GgmxqdJQA1mQHb0pas6ZW8/s334/Screenshot_2024-04-20_at_4.22.10_PM-removebg-preview.png">
                  {% else %}
                  <img class="rating_email" style="rotate: -90deg; width: auto; height: 8vh;"
                    src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhD2a2uzprPRdusoiSCTdrF5I6j5T_nY4FD-PU4e62iy0B77leCdAAiBhAcwa5R_p40HiDPkoX0Q_cBKONCbj3O7tq-lxhO2paTdCivtc2lG9hL_w5aVHxhH6cz5zUnGqAEcpU0kt2cGPVf5V6DmIU9AOHWaQXNCyh7g4cR2GgmxqdJQA1mQHb0pas6ZW8/s334/Screenshot_2024-04-20_at_4.22.10_PM-removebg-preview.png">
                  {% endif %}

                  {% if report.private %}
                  <img class="private" style="width: auto; height: 12vh;"
                    src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhAzIyj1_OYAFmTj3BUckj9dXwIibMGwLCQsYzr6YKgV1M3FNgXAmOteI0BtQ4Q8opFuJtse9Z6pWpm_WHO3oKlJRVn7lGy-dUj_bZyVAjZtYeDw1AgUh0iuebQHGgOiXMgA77o4x-yoA5pv0I-TJjkgRtlqP4PLxP4xgviSeVRzbQSsIIGrV74AWe-bEg/s499/Screenshot_2024-04-20_at_4.54.16_PM-removebg-preview.png">
                  {% else %}
                  <img class="private" style="width: auto; height: 12vh;"
                    src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhQ52KOYGpyxrFzwPHlPSzPTy4q2_ia3ZY_2lS4V_LeK17q-GsnV2Oz9N4rjo3DFGTUM_tCukP1NdjkxR0WPIboS_Ic7T8ZVEvlTkgB7MTZtWbRNIIe_me9kYRG6v_F_QcUpT-UNkqQs4V_Wt99_eMAHz09cNZwHMcRTsiKtnsHIN8kipt2qKml5YCzfhQ/s499/Screenshot_2024-04-20_at_4.53.59_PM-removebg-preview.png">
                  {% endif %}

                  {% if report.email_prof %}
                  <img class="rating_email" style="width: auto; height: 8vh;"
                    src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiNX84xbjujhq0k_nn7jxNdXbH3oKWv7mIcWS1qeMnd2jXEvVnbjFNaf_IDtTNu_HiWZ5psck04nLQtpUvF9EpieL-SKEAzwE4BVURr-EgSlxM8BtqbFLHacFGj1GQgtHU1FrOAqUmVKRFJ6wuRnGBhtM-6LFfYSHFwfE-3r3e83bhvL_UijC1is6NXWL8/s430/Screenshot_2024-04-20_at_4.25.21_PM-removebg-preview.png">
                  {% else %}
                  <img class="rating_email" style="width: auto; height: 8vh;"
                    src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiLi8glhGxlrEbBO5YRVmS0ijCmryyCYfM-EBCDXSIpmoewulXh7q9T5DLDVZowRRFaktpqRwAUpUhJtWjE2-s3nZ5zu9yDDBWnojEVeBE_Sohi64yG5GYwyrXYReNbF6wE6ZE8FmD9_xcOfGdcL_TmRDSzBSPS67Q4pdwWJG-jD7Lhyphenhyphenus1GnKuVMhmLw0/s500/Screenshot_2024-04-20_at_4.27.50_PM-removebg-preview.png">
                  {% endif %}
                </div>

              </div>

            </div>

          </div>
          <strong style="margin-left: auto; margin-right: auto; margin-top: 10px; display: block;">Admin Feedback: {% if report.feedback == "" %}Pending{% endif %}</strong>
          <div class="textarea-container" style="width: 100%; display: flex; justify-content: center;">
                    
            <textarea readonly placeholder= "View full report to give feedback" style="background-color:rgb(237, 237, 237); width: 90%; border-radius: 5px; margin-bottom: 10px; padding: 10px; resize: vertical; min-height: 100px;" rows="4" class="report">{{report.feedback}}</textarea>
          </div>
          <div style="margin-top: 10px; margin-bottom: 10px; margin-left: 5px; height: 5vh; margin-left: auto; margin-right: auto;">
            <div style="display: flex;">
              <a href="/adminreportview/{{report.pk}}/"
                style="font-size: 20px; font-weight: 300; width: 10vw; border-radius: 5px; margin-right: 5px; height: 5vh; display: flex; justify-content: center; align-items: center; background-color: #81B29A; text-decoration: none; color: white; word-break: break-all; text-align: center;">
                View
              </a>
              <form action="{% url 'login:report_delete' report.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="delete"
                  style="font-size: 20px; font-weight: 300; width: 10vw; height: 5vh; background-color: rgb(224, 122, 95); color: white; border: 0px; border-radius: 5px; text-align: center; word-break: break-all;">
                  Delete
                </button>
              </form>
            </div>
          </div>
        </div>

      </div>
      {% empty %}
      <p style="font-size: 200%; color: black; text-align: center;">No Public Reports</p>
      {% endfor %}
    </div>
  </div>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var publicReports = document.getElementById('public');
      var publicreps = document.getElementById('Public');
      if (publicReports) {
        publicReports.style.backgroundColor = 'rgb(242, 204, 143)';
        publicreps.style.height = '90px';
        publicReports.style.width = '120px';
        publicReports.style.transform = 'translateY(0px)';
        publicReports.style.borderBottomLeftRadius = '8px';
        publicReports.style.borderBottomRightRadius = '8px';
        publicreps.style.boxShadow = '0px 6px 10px rgba(0, 0, 0, 0.65)';
        publicreps.style.borderBottomLeftRadius = '8px';
        publicreps.style.borderBottomRightRadius = '8px';
      }
    });
  </script>
</body>

</html>

login/templates/email_sent.html
<!DOCTYPE html>
{% load socialaccount %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<style>
    body {
        font-family: 'Lato', sans-serif;
    }
    </style>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap">

<html lang="en">
    {% include 'login/admin_navbar.html' %}
    <body style="background-color: rgb(224, 122, 95); margin-top: 120px;" class="body">
        <h1 class="mb-4">{{ message }}</h1>
        <a class="btn btn-primary" style="background-color: #3D405B" href="/adminreportview/" role="button">Back to Reports</a>
    </body>
</html>

login/templates/index.html
{% load socialaccount %}
<html>
  <style>
    body {
        font-family: 'Lato', sans-serif;
    }
    </style>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap">

<body>
<h1>My Google OAuth Project </h1>
{% if user.is_authenticated %}
  <p>Welcome, You are logged in as {{ user.username }}</p>
  <p>Your email is {{user.email}} </p>
  <a href="logout"> Logout </a>
{% else %}
{% endif %}
</body>
</html>

login/templates/temp_admin_report_view.html
<!DOCTYPE html>
{% load socialaccount %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<style>
    body {
        font-family: 'Lato', sans-serif;
    }
    </style>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap">

<html lang="en">
    {% include 'login/admin_navbar.html' %}
    {% if user.is_authenticated %}
        {% if user.groups.exists %}
        {% for group in user.groups.all %}
            {% if group.name == 'site admin' %}
                {% endif %}
            {% endfor %}
        {% else %}
            <meta http-equiv="refresh" content="0; url=/userlanding/" />
        {% endif %}
    {% endif %}
    <div class="d-flex justify-content-center mt-3">
        <ul class="mt-3">
            {% for report in reports %}
                    <li><a href="/adminreportview/{{report.pk}}/">View Report #{{ report.pk }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <body>
        
    </body>
</html>